### ISSUE TITLE
Crash during server startup

### ISSUE THREAD

**Issue by danisztls** [jspricke/radicale-storage#16]
```
[CRITICAL] An exception occurred during server startup: Failed to load storage module 'radicale_remind': cannot import name 'Item' from 'radicale.storage' (/home/lobo/Workshop/source/workshop/remind-test/env/lib/python3.8/site-packages/radicale/storage/__init__.py)
```
Fresh virtual environment with radicale and radicale-remind packages installed.

**Comment by jspricke** [comment]
which versions of radicale and radicale did you use?

**Comment by danisztls** [comment]
radicale 3.0.3
radicale-remind 0.2.5

I don't know if it is a problem but I have radicale installed through pacman, configured and running in my system. But I did the test with them installed in a virtual environment, system service stopped, and custom configuration parsed through -C flag in radicale with custom port and paths.

**Comment by jspricke** [comment]
* Daniel <notifications@github.com> [2020-07-23 18:01]:
>radicale 3.0.3
>radicale-remind 0.2.5

radicale-remind 0.2.5 only works with radicale 2.1.9, the git master 
works with 3.0.3 for me. I can make a new release if it works for you as 
well.

**Comment by danisztls** [comment]
I may try the git master later but your other project remind-caldav is perfect for my use case.
